name: Run Tests # name of GitHub Actions Workflow
on: # triggered on push or pull request
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs: # create a job called Run Tests
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    env:
      TESTING: true
    steps:
      - name: Checkout Repository # check out the repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.4'

      - name: Setup Python Virtual Environment
        run: python -m venv python3-virtualenv

      - name: Install Dependencies
        run: python3-virtualenv/bin/pip install -r requirements.txt

      - name: Run Tests
        run: |
          chmod +x ../../run_test.sh
          ../../run_test.sh
